### ISSUE TITLE
Reconsider PR checks

### ISSUE THREAD

**Issue by ademenkova** [lcdsmao/update-branch#255]
Hello,

Using the action I’ve faced a situation when some PRs are not processed even if all required conditions are met. 
After analysing the code I found this check:
https://github.com/lcdsmao/update-branch/blob/cae64215f47ed8aec706060b74672e1d36df28c1/src/utils.ts#L40

  In my case, I'm requesting 6 reviews, however, according to the branch protection rules only 1 approval is required. So, pr.reviewRequests.totalCount can be greater than condition.requiredApprovals and will never be equal to 0 .

Here is my action.yaml: 
```
name: Auto Update/Merge branch

on:
  push:
    branches: [release]
  workflow_dispatch:

jobs:
  Update-merge-branch:
    runs-on: [ self-hosted ]
    steps:
      - uses: lcdsmao/update-branch@v3.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          autoMergeMethod: SQUASH
          protectedBranchNamePattern: release
```
 
Could you please consider this issue?
